"use client";

import { BadgePoundSterling, CircleGauge, FileCheck2, HeartHandshake, LockKeyhole, PlugZap, ScrollText, ShieldAlert, UserRoundCheck } from "lucide-react";
import { useState } from "react";

import { Button } from "@/components/ui/button";
import { Status } from "@/components/ui/status";

const panel = "rounded-2xl border border-border-strong bg-background p-5 sm:p-7";

export function ClubGovernanceScreen({ section, role = "club-admin" }: { section: string; role?: "club-admin" | "treasurer" | "welfare-officer" }) {
  if (section === "payments") return <FinanceDashboard />;
  if (section === "forms" || section === "consents") return <ConsentDashboard section={section} />;
  if (section === "compliance") return <ComplianceDashboard />;
  if (section === "safeguarding") return <SafeguardingDashboard role={role} />;
  if (section === "reports") return <ReportingDashboard />;
  if (["settings", "integrations", "entitlements"].includes(section)) return <ClubSettings section={section} />;
  return null;
}

function FinanceDashboard() {
  const [reconciled, setReconciled] = useState(false);
  return <section data-testid="club-payments" className="space-y-5" aria-labelledby="finance-title"><div className="grid gap-4 sm:grid-cols-3">{[["Collected", "£4,875.00"], ["Outstanding", "£750.00"], ["Refunds", "£60.00"]].map(([label, value]) => <article key={label} className={panel}><p className="text-xs font-semibold uppercase tracking-[0.12em] text-muted">{label}</p><p className="mt-3 text-2xl font-semibold">{value}</p></article>)}</div><div className={panel}><div className="flex flex-wrap items-center justify-between gap-4"><div><Status tone="info">Treasurer workspace</Status><h2 id="finance-title" className="mt-4 text-xl font-semibold">Member payments and reconciliation</h2></div><BadgePoundSterling className="size-7 text-primary-strong" aria-hidden="true"/></div><div aria-labelledby="finance-title" className="mt-6 overflow-x-auto focus-visible:outline-none focus-visible:ring-3 focus-visible:ring-ring/35" tabIndex={0}><table className="w-full min-w-[34rem] text-left text-sm"><thead><tr className="border-b border-border text-muted"><th className="px-3 py-3">Invoice</th><th className="px-3 py-3">Household</th><th className="px-3 py-3">Amount</th><th className="px-3 py-3">State</th></tr></thead><tbody><tr><td className="px-3 py-4">GR-2026-014</td><td className="px-3 py-4">Morgan household</td><td className="px-3 py-4">£125.00</td><td className="px-3 py-4"><Status tone="warning">Due</Status></td></tr><tr className="border-t border-border"><td className="px-3 py-4">GR-2026-009</td><td className="px-3 py-4">Taylor household</td><td className="px-3 py-4">£150.00</td><td className="px-3 py-4"><Status tone="success">Paid</Status></td></tr></tbody></table></div><Button className="mt-5" onClick={() => setReconciled(true)} type="button">Preview cash reconciliation</Button>{reconciled ? <p role="status" className="mt-4 rounded-xl bg-warning-soft px-4 py-3 text-sm font-semibold text-warning-strong">Demo variance: expected £45.00, counted £44.20. Nothing was posted.</p> : null}</div></section>;
}

function ConsentDashboard({ section }: { section: string }) {
  const [previewed, setPreviewed] = useState(false);
  return <section data-testid={`club-${section}`} className="grid gap-5 lg:grid-cols-[1.25fr_0.75fr]"><div className={panel}><div className="flex items-center gap-3"><FileCheck2 className="size-5 text-primary-strong" aria-hidden="true"/><h2 className="text-xl font-semibold">Versioned club forms</h2></div><p className="mt-2 text-sm leading-6 text-muted">Publishing a new version asks guardians to respond again. Historic answers and withdrawals remain immutable.</p><article className="mt-6 rounded-xl bg-surface p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-semibold">Photo and video consent</h3><p className="mt-1 text-sm text-muted">Version 3 · 8 of 9 responses</p></div><Status tone="warning">1 needed</Status></div></article><Button className="mt-5" type="button" onClick={() => setPreviewed(true)}>Preview new version</Button>{previewed ? <p role="status" className="mt-4 rounded-xl bg-info-soft p-4 text-sm font-semibold text-info-strong">Demo only: version 4 is previewed and was not published.</p> : null}</div><aside className="rounded-2xl bg-ink p-5 text-white sm:p-7"><p className="text-xs font-semibold uppercase tracking-[0.15em] text-white/65">Consent health</p><p className="mt-4 text-4xl font-semibold">89%</p><p className="mt-3 text-sm leading-6 text-white/70">Current-version responses for Under 11s. Withdrawn consent is never counted as valid.</p></aside></section>;
}

function ComplianceDashboard() {
  return <section data-testid="club-compliance" className="space-y-5"><div className={panel}><div className="flex items-center gap-3"><UserRoundCheck className="size-5 text-primary-strong" aria-hidden="true"/><h2 className="text-xl font-semibold">Workforce compliance</h2></div><div className="mt-6 grid gap-3 sm:grid-cols-2"><article className="rounded-xl bg-warning-soft p-4"><Status tone="warning">Expires in 11 days</Status><h3 className="mt-3 font-semibold">Sam Taylor · Emergency Aid</h3><p className="mt-1 text-sm text-muted">Valid until 1 August 2026</p></article><article className="rounded-xl bg-surface p-4"><Status tone="success">Current</Status><h3 className="mt-3 font-semibold">Priya Shah · Safeguarding</h3><p className="mt-1 text-sm text-muted">Valid until 16 February 2027</p></article></div></div><div className={panel}><h2 className="text-lg font-semibold">Equipment and volunteer readiness</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><p className="rounded-xl bg-surface p-4 text-sm"><strong>18 match shirts</strong><br/><span className="text-muted">Checked out to Under 11s</span></p><p className="rounded-xl bg-warning-soft p-4 text-sm"><strong>1 rota gap</strong><br/><span className="text-muted">Welcome desk · Saturday</span></p></div></div></section>;
}

function SafeguardingDashboard({ role }: { role: string }) {
  const permitted = role === "welfare-officer";
  const [feedback, setFeedback] = useState<string | null>(null);
  return <section data-testid="club-safeguarding" className="max-w-4xl" aria-labelledby="safeguarding-title"><div className="rounded-2xl border border-danger/30 bg-background p-5 sm:p-7"><div className="flex items-start gap-4"><div className="rounded-xl bg-danger-soft p-3"><ShieldAlert className="size-6 text-danger-strong" aria-hidden="true"/></div><div><Status tone="danger">Restricted</Status><h2 id="safeguarding-title" className="mt-3 text-xl font-semibold">Safeguarding case workspace</h2><p className="mt-2 text-sm leading-6 text-muted">Concern details are available to welfare officers only. Every allowed or denied access writes a metadata-only audit record.</p></div></div>{permitted ? <div className="mt-6 rounded-xl bg-surface p-4"><p className="text-sm font-semibold">1 open concern</p><p className="mt-1 text-sm text-muted">Open the restricted record to continue the welfare workflow.</p><Button className="mt-4" type="button" onClick={() => setFeedback("Demo only: audited concern access was previewed; no restricted record was opened.")}>Preview audited open</Button></div> : <div className="mt-6 flex items-start gap-3 rounded-xl bg-danger-soft p-4 text-sm text-danger-strong"><LockKeyhole className="mt-0.5 size-5 shrink-0" aria-hidden="true"/><p><strong>Detail hidden.</strong> Club administrators can raise a concern but cannot browse case content.</p></div>}<Button className="mt-5" variant="secondary" type="button" onClick={() => setFeedback("Demo only: the new concern form was previewed and no record was saved.")}>Preview new concern</Button>{feedback ? <p role="status" className="mt-4 rounded-xl bg-info-soft p-4 text-sm font-semibold text-info-strong">{feedback}</p> : null}</div></section>;
}

function ReportingDashboard() {
  const [previewed, setPreviewed] = useState(false);
  return <section data-testid="club-reports" className="grid gap-5 lg:grid-cols-2"><div className={panel}><div className="flex items-center gap-3"><ScrollText className="size-5 text-primary-strong"/><h2 className="text-xl font-semibold">Permission-filtered reports</h2></div><p className="mt-3 text-sm leading-6 text-muted">Exports are watermarked, formula-safe and recorded. Sensitive medical and welfare bodies are excluded.</p><Button className="mt-5" type="button" onClick={() => setPreviewed(true)}>Preview member export</Button>{previewed ? <p role="status" className="mt-4 rounded-xl bg-info-soft p-4 text-sm font-semibold text-info-strong">Demo only: a redacted, watermarked export was previewed and no file was generated.</p> : null}</div><div className={panel}><div className="flex items-center gap-3"><HeartHandshake className="size-5 text-primary-strong"/><h2 className="text-xl font-semibold">Retention and deletion</h2></div><p className="mt-3 text-sm leading-6 text-muted">Three deletion jobs are scheduled after their legal-retention checks. Account export remains available to the data subject.</p><Status className="mt-5" tone="info">Next job · 02:00</Status></div></section>;
}

function ClubSettings({ section }: { section: string }) {
  const data = section === "integrations" ? { icon: PlugZap, title: "Provider integrations", copy: "Stripe is not connected. Manual development payments remain visibly non-card and require treasurer confirmation.", status: "Not connected" } : section === "entitlements" ? { icon: CircleGauge, title: "Club entitlements", copy: "Founding club pricing is recorded independently from member payments and never changes invoice ledgers.", status: "Founding entitlement" } : { icon: CircleGauge, title: "Organisation lifecycle", copy: "Ownership transfer requires the current owner. Deletion is delayed for 30 days and retention jobs are audited.", status: "14-day trial" };
  const Icon = data.icon;
  return <section data-testid={`club-${section}`} className="max-w-4xl"><div className={panel}><div className="flex items-center gap-3"><Icon className="size-5 text-primary-strong"/><h2 className="text-xl font-semibold">{data.title}</h2></div><p className="mt-3 text-sm leading-6 text-muted">{data.copy}</p><Status className="mt-5" tone="info">{data.status}</Status></div></section>;
}
