"use client";

import { useState } from "react";

import { Button } from "@/components/ui/button";
import { saveProductionTrainingPlan } from "@/features/coaching/actions";

export type BuilderItem = { key: string; kind: "segment" | "drill"; title: string; drillId: string; durationMinutes: number; participantFocus: string; equipment: string; area: string; setup: string; diagramUrl: string; instructions: string; coachingPoints: string; progression: string; regression: string; safety: string; inclusion: string; goalkeeper: string; notes: string };
export type TrainingTemplateOption = { id: string; title: string; durationMinutes: number; items: BuilderItem[] };
const blank = (kind: BuilderItem["kind"], key: string): BuilderItem => ({ key, kind, title: kind === "segment" ? "Arrival and activation" : "", drillId: "", durationMinutes: 10, participantFocus: "Whole group", equipment: "", area: "", setup: "", diagramUrl: "", instructions: "", coachingPoints: "", progression: "", regression: "", safety: "", inclusion: "", goalkeeper: "", notes: "" });

export function ProductionTrainingBuilder({ workspace, section, events, drills, templates = [], sessionId, initialTitle = "Team training", initialDuration = 60, initialItems }: { workspace: string; section: string; events: { id: string; label: string }[]; drills: { id: string; label: string }[]; templates?: TrainingTemplateOption[]; sessionId?: string; initialTitle?: string; initialDuration?: number; initialItems?: BuilderItem[] }) {
  const [items, setItems] = useState<BuilderItem[]>(initialItems?.length ? initialItems : [blank("segment", "initial-segment")]);
  const [duration, setDuration] = useState(initialDuration);
  const update = (key: string, patch: Partial<BuilderItem>) => setItems((current) => current.map((item) => item.key === key ? { ...item, ...patch } : item));
  const serialised = JSON.stringify(items.map(({ equipment, ...item }) => ({ ...item, drillId: item.kind === "drill" ? item.drillId : undefined, equipment: equipment.split(",").map((value) => value.trim()).filter(Boolean) })));
  const allocated = items.reduce((total, item) => total + item.durationMinutes, 0);
  const move = (index: number, delta: number) => setItems((current) => { const next = [...current]; const target = index + delta; if (target < 0 || target >= next.length) return current; [next[index], next[target]] = [next[target]!, next[index]!]; return next; });
  return <form action={saveProductionTrainingPlan} className="mt-5 grid gap-4"><input type="hidden" name="workspace" value={workspace}/><input type="hidden" name="section" value={section}/><input type="hidden" name="itemsJson" value={serialised}/>{sessionId ? <input type="hidden" name="sessionId" value={sessionId}/> : <label className="text-sm font-semibold">Training event<select className="mt-2 min-h-11 w-full rounded-[10px] border border-border-strong bg-background px-3" name="eventInstanceId">{events.map((event) => <option key={event.id} value={event.id}>{event.label}</option>)}</select></label>}<div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Plan title<input className="mt-2 min-h-11 w-full rounded-[10px] border border-border-strong bg-background px-3" name="title" defaultValue={initialTitle} required/></label><label className="text-sm font-semibold">Total minutes<input className="mt-2 min-h-11 w-full rounded-[10px] border border-border-strong bg-background px-3" name="durationMinutes" type="number" min="10" max="240" value={duration} onChange={(event) => setDuration(Number(event.target.value))} required/></label></div>
    {templates.length && !sessionId ? <label className="text-sm font-semibold">Start from a reusable template<select className="mt-2 min-h-11 w-full rounded-[10px] border border-border-strong px-3" defaultValue="" onChange={(event) => { const template = templates.find((item) => item.id === event.target.value); if (template) { setItems(template.items.map((item,index) => ({ ...item, key: `${template.id}-${index}` }))); setDuration(template.durationMinutes); } }}><option value="">Blank plan</option>{templates.map((template) => <option key={template.id} value={template.id}>{template.title}</option>)}</select></label> : null}
    <p className={`rounded-lg px-3 py-2 text-sm font-semibold ${allocated > duration ? "bg-danger-soft text-danger" : "bg-success-soft text-success"}`} role="status">{allocated} minutes allocated · {Math.max(0, duration - allocated)} minutes unallocated{allocated > duration ? ` · ${allocated - duration} minutes over` : ""}</p>
    {items.map((item, index) => <fieldset className="rounded-xl border border-border p-4" key={item.key}><legend className="px-2 font-semibold">{index + 1}. {item.kind === "segment" ? "Session segment" : "Library drill"}</legend><div className="grid gap-3 sm:grid-cols-2">{item.kind === "segment" ? <label className="text-sm font-semibold">Title<input className="mt-2 min-h-11 w-full rounded-[10px] border border-border-strong px-3" value={item.title} onChange={(event) => update(item.key,{ title: event.target.value })}/></label> : <label className="text-sm font-semibold">Drill<select className="mt-2 min-h-11 w-full rounded-[10px] border border-border-strong px-3" value={item.drillId} onChange={(event) => update(item.key,{ drillId: event.target.value })}><option value="">Choose a drill</option>{drills.map((drill) => <option key={drill.id} value={drill.id}>{drill.label}</option>)}</select></label>}<label className="text-sm font-semibold">Minutes<input className="mt-2 min-h-11 w-full rounded-[10px] border border-border-strong px-3" type="number" min="1" value={item.durationMinutes} onChange={(event) => update(item.key,{ durationMinutes: Number(event.target.value) })}/></label>{([['participantFocus','Players / group'],['equipment','Equipment'],['area','Area'],['setup','Set-up'],['diagramUrl','Set-up diagram URL'],['instructions','Instructions'],['coachingPoints','Coaching points'],['progression','Progression'],['regression','Regression'],['safety','Safety'],['inclusion','Inclusion adaptation'],['goalkeeper','Goalkeeper adaptation'],['notes','Coach notes']] as const).map(([property,label]) => <label className="text-sm font-semibold" key={property}>{label}<input className="mt-2 min-h-11 w-full rounded-[10px] border border-border-strong px-3" value={item[property]} onChange={(event) => update(item.key,{ [property]: event.target.value })}/></label>)}</div><div className="mt-3 flex flex-wrap gap-2"><Button variant="secondary" type="button" onClick={() => move(index,-1)} disabled={index === 0}>Move up</Button><Button variant="secondary" type="button" onClick={() => move(index,1)} disabled={index === items.length - 1}>Move down</Button><Button variant="secondary" type="button" onClick={() => setItems((current) => current.filter((candidate) => candidate.key !== item.key))} disabled={items.length === 1}>Remove</Button></div></fieldset>)}
    <div className="flex flex-wrap gap-3"><Button variant="secondary" type="button" onClick={() => setItems((current) => [...current, blank("segment", `segment-${Date.now()}-${current.length}`)])}>Add segment</Button><Button variant="secondary" type="button" onClick={() => setItems((current) => [...current, blank("drill", `drill-${Date.now()}-${current.length}`)])} disabled={!drills.length}>Add drill</Button><Button type="submit">{sessionId ? "Save plan changes" : "Create training plan"}</Button></div>
  </form>;
}
